name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      MONGODB_URI: mongodb://localhost:27017/test
      NEXTAUTH_SECRET: testSecret
      NEXTAUTH_URL: http://localhost:3000
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - name: wait for mongodb to start
        run: sleep 5
      
      - name: TypeScript Check
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Build Next.js
        run: npm run build

      - name: Build Server
        run: npm run build:server